# Generated by Django 5.1.6 on 2025-03-20 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YMC', '0002_blog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, help_text='optional', max_length=120, unique=True),
        ),
    ]
