# Generated by Django 5.1.6 on 2025-03-21 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_story'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='video',
        ),
    ]
